"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import LuxIcon from "@/components/lux-icons";
import type { RuntimeContent } from "@/lib/types";

type Props = {
  data: RuntimeContent;
};

type LeadForm = {
  name: string;
  email: string;
  company: string;
  interest: string;
  message: string;
};

type Audience = "client" | "recruiter" | "partner";

const audienceConfig: Record<Audience, { label: string; subtitle: string; interest: string; cta: string }> = {
  client: {
    label: "Client Project",
    subtitle: "Launch or scale a premium product",
    interest: "Project Inquiry",
    cta: "Build Your Product Roadmap"
  },
  recruiter: {
    label: "Recruiter Hiring",
    subtitle: "Evaluate role fit and delivery quality",
    interest: "Job Opportunity",
    cta: "Start Hiring Conversation"
  },
  partner: {
    label: "Strategic Partnership",
    subtitle: "Collaborate on market-facing initiatives",
    interest: "Partnership",
    cta: "Open Partnership Discussion"
  }
};

const initialLead: LeadForm = {
  name: "",
  email: "",
  company: "",
  interest: audienceConfig.client.interest,
  message: ""
};

function formatNumber(value: number | null): string {
  return value === null ? "--" : new Intl.NumberFormat("en-US").format(value);
}

function useAnimatedCounter(target: number | null, duration = 1100) {
  const [value, setValue] = useState(0);

  useEffect(() => {
    if (target === null || target < 0) {
      setValue(0);
      return;
    }

    let frame = 0;
    const begin = performance.now();

    const tick = (time: number) => {
      const progress = Math.min((time - begin) / duration, 1);
      const eased = 1 - Math.pow(1 - progress, 3);
      setValue(Math.round(target * eased));
      if (progress < 1) frame = requestAnimationFrame(tick);
    };

    frame = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(frame);
  }, [target, duration]);

  return value;
}

export default function LuxuryPortfolioClient({ data }: Props) {
  const [liveData, setLiveData] = useState<RuntimeContent>(data);
  const [query, setQuery] = useState("");
  const [tag, setTag] = useState<"all" | "web" | "ai" | "data" | "enterprise">("all");
  const [viewMode, setViewMode] = useState<"curated" | "all">("all");
  const [audience, setAudience] = useState<Audience>("client");
  const [leadStep, setLeadStep] = useState<1 | 2 | 3>(1);
  const [lead, setLead] = useState<LeadForm>(initialLead);
  const [leadState, setLeadState] = useState<"idle" | "saving" | "done" | "error">("idle");
  const [leadError, setLeadError] = useState("");

  useEffect(() => {
    let isMounted = true;

    async function refreshProfile() {
      try {
        const response = await fetch("/api/profile", { cache: "no-store" });
        if (!response.ok) return;
        const latest = (await response.json()) as RuntimeContent;
        if (isMounted) setLiveData(latest);
      } catch {
        // keep existing UI when refresh fails
      }
    }

    const interval = setInterval(refreshProfile, 60000);
    return () => {
      isMounted = false;
      clearInterval(interval);
    };
  }, []);

  useEffect(() => {
    setLead((previous) => ({ ...previous, interest: audienceConfig[audience].interest }));
  }, [audience]);

  const runtimeLabel = new Date(liveData.runtime.generatedAt).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
    timeZone: liveData.runtime.timezone
  });

  const filteredProjects = useMemo(() => {
    const normalized = query.trim().toLowerCase();
    return liveData.projects.filter((project) => {
      if (viewMode === "curated" && project.autogenerated) return false;
      const tagMatch = tag === "all" || project.tags.includes(tag);
      if (!tagMatch) return false;
      if (!normalized) return true;
      return `${project.title} ${project.stack} ${project.summary.join(" ")}`.toLowerCase().includes(normalized);
    });
  }, [liveData.projects, query, tag, viewMode]);

  const caseStudySlugs = useMemo(() => new Set(liveData.caseStudies.map((study) => study.slug)), [liveData.caseStudies]);
  const followerCount = useAnimatedCounter(liveData.runtime.githubFollowers);
  const repoCount = useAnimatedCounter(liveData.runtime.githubRepos);
  const starCount = useAnimatedCounter(liveData.runtime.totalStars);

  async function submitLeadWithError(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    if (leadStep < 3) return;
    setLeadState("saving");
    setLeadError("");

    try {
      const response = await fetch("/api/leads", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(lead)
      });
      const payload = (await response.json()) as { ok?: boolean; error?: string };
      if (!response.ok || !payload.ok) {
        throw new Error(payload.error ?? "Failed to submit inquiry.");
      }
      setLeadState("done");
      setLead(initialLead);
      setLeadStep(1);
      setAudience("client");
    } catch (error) {
      setLeadState("error");
      setLeadError(error instanceof Error ? error.message : "Could not send inquiry.");
    }
  }

  const canProceedStepTwo = lead.name.trim().length >= 2 && lead.email.trim().length >= 5;
  const canSubmit = lead.message.trim().length >= 5;

  return (
    <main>
      <div className="spotlight spotlight-gold" />
      <div className="spotlight spotlight-blue" />

      <header className="top-nav" data-reveal>
        <div className="container nav-wrap">
          <p className="brand">{liveData.profile.name}</p>
          <nav>
            <Link className="nav-link" data-magnetic data-magnetic-strength="8" href="/">
              Home
            </Link>
            <Link className="nav-link" data-magnetic data-magnetic-strength="8" href="/services">
              Services
            </Link>
            <Link className="nav-link" data-magnetic data-magnetic-strength="8" href="/case-studies">
              Case Studies
            </Link>
            <Link className="nav-link" data-magnetic data-magnetic-strength="8" href="/blog">
              Insights
            </Link>
            <Link className="nav-link" data-magnetic data-magnetic-strength="8" href="/recruiters">
              Recruiters
            </Link>
          </nav>
        </div>
      </header>

      <section className="hero" data-reveal>
        <div className="halo halo-one" />
        <div className="halo halo-two" />
        <div className="container hero-shell">
          <div className="hero-copy">
            <p className="eyebrow">Luxury Enterprise Portfolio</p>
            <h1>{liveData.profile.name}</h1>
            <p className="lead">{liveData.profile.tagline}</p>
            <p className="sublead">{liveData.profile.about}</p>
            <div className="runtime-bar">
              <span>Live Snapshot: {runtimeLabel}</span>
              <span>Location: {liveData.profile.city}</span>
            </div>
            <div className="cta-row">
              <a className="btn btn-gold" data-magnetic href={liveData.profile.cvPath} target="_blank" rel="noreferrer">
                Download CV
              </a>
              <a className="btn btn-outline" data-magnetic href={liveData.profile.github} target="_blank" rel="noreferrer">
                GitHub
              </a>
              <a className="btn btn-outline" data-magnetic href={`mailto:${liveData.profile.email}`}>
                Direct Email
              </a>
            </div>
          </div>
          <div className="hero-panel card" data-reveal>
            <p className="eyebrow">Executive Snapshot</p>
            <div className="metrics metrics-single">
              <article className="metric-card">
                <p className="metric-value">{followerCount ? formatNumber(followerCount) : formatNumber(liveData.runtime.githubFollowers)}</p>
                <p className="metric-label">GitHub Followers</p>
              </article>
              <article className="metric-card">
                <p className="metric-value">{repoCount ? formatNumber(repoCount) : formatNumber(liveData.runtime.githubRepos)}</p>
                <p className="metric-label">Public Repositories</p>
              </article>
              <article className="metric-card">
                <p className="metric-value">{starCount ? formatNumber(starCount) : formatNumber(liveData.runtime.totalStars)}</p>
                <p className="metric-label">Total Stars</p>
              </article>
            </div>
            <div className="status-pills">
              <span>Response Window: &lt; 24h</span>
              <span>Open To: Enterprise / Product / AI Roles</span>
            </div>
            <p className="repo-meta">Auto-synced with GitHub every 60 seconds</p>
          </div>
        </div>
      </section>

      <section className="section" data-reveal>
        <div className="container">
          <div className="logos-marquee">
            <div className="logos-track">
              {[...liveData.clientLogos, ...liveData.clientLogos].map((logo, index) => (
                <span key={`${logo}-${index}`}>{logo}</span>
              ))}
            </div>
          </div>
        </div>
      </section>

      <section className="section" data-reveal>
        <div className="container three-col">
          <article className="card premium-card" data-reveal>
            <LuxIcon name="architecture" className="lux-icon" />
            <p className="eyebrow">01</p>
            <h3>Product Architecture</h3>
            <p>Clean, scalable system design with maintainable components and production-safe engineering decisions.</p>
          </article>
          <article className="card premium-card" data-reveal>
            <LuxIcon name="intelligence" className="lux-icon" />
            <p className="eyebrow">02</p>
            <h3>Data and Intelligence</h3>
            <p>Applied ML and analytics pipelines that are explainable, business-ready, and built for adoption.</p>
          </article>
          <article className="card premium-card" data-reveal>
            <LuxIcon name="conversion" className="lux-icon" />
            <p className="eyebrow">03</p>
            <h3>Conversion-Centered UX</h3>
            <p>Luxury-grade interfaces engineered to build trust, increase engagement, and convert high-value leads.</p>
          </article>
        </div>
      </section>

      <section className="section" data-reveal>
        <div className="container">
          <div className="section-head">
            <p className="eyebrow">Portfolio Intelligence</p>
            <h2>Interactive Project Explorer</h2>
          </div>
          <div className="project-toolbar">
            <input
              className="lux-input"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Search projects, technologies, use cases"
            />
            <div className="chip-row">
              <button
                type="button"
                data-magnetic
                className={`chip ${viewMode === "curated" ? "chip-active" : ""}`}
                onClick={() => setViewMode("curated")}
              >
                Curated
              </button>
              <button
                type="button"
                data-magnetic
                className={`chip ${viewMode === "all" ? "chip-active" : ""}`}
                onClick={() => setViewMode("all")}
              >
                All GitHub
              </button>
            </div>
            <div className="chip-row">
              {["all", "web", "ai", "data", "enterprise"].map((item) => (
                <button
                  key={item}
                  type="button"
                  data-magnetic
                  className={`chip ${tag === item ? "chip-active" : ""}`}
                  onClick={() => setTag(item as typeof tag)}
                >
                  {item.toUpperCase()}
                </button>
              ))}
            </div>
          </div>
          <p className="result-meta">
            Showing {filteredProjects.length} projects in {viewMode === "curated" ? "Curated" : "All GitHub"} mode
            {viewMode === "all" ? ` (including ${liveData.runtime.syncedRepos} auto-synced from GitHub)` : ""}
          </p>
          <div className="project-grid">
            {filteredProjects.map((project) => (
              <article key={project.slug} className="card project-card" data-reveal>
                <p className="stack">{project.stack}</p>
                <h3>{project.title}</h3>
                {project.autogenerated && <p className="repo-meta">Auto-synced GitHub repository</p>}
                <ul>
                  {project.summary.map((line) => (
                    <li key={line}>{line}</li>
                  ))}
                </ul>
                <p className="repo-meta">
                  Signals: {formatNumber(project.stars ?? null)} stars | {formatNumber(project.forks ?? null)} forks
                </p>
                <div className="project-links">
                  {project.github && (
                    <a href={project.github} target="_blank" rel="noreferrer">
                      GitHub
                    </a>
                  )}
                  {caseStudySlugs.has(project.slug) ? (
                    <Link href={`/case-studies/${project.slug}`}>Case Study</Link>
                  ) : (
                    <Link href="/case-studies">Case Studies</Link>
                  )}
                </div>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section className="section" data-reveal>
        <div className="container three-col">
          <article className="card" data-reveal>
            <h2>Services</h2>
            <ul>
              {liveData.services.map((service) => (
                <li key={service.slug}>
                  <p className="list-title">{service.title}</p>
                  <p>{service.description}</p>
                </li>
              ))}
            </ul>
            <Link className="inline-link" href="/services">
              View all services
            </Link>
          </article>
          <article className="card" data-reveal>
            <h2>Testimonials</h2>
            {liveData.testimonials.map((testimonial) => (
              <blockquote key={testimonial.name} className="testimonial">
                <p>"{testimonial.quote}"</p>
                <cite>
                  {testimonial.name} | {testimonial.role}
                </cite>
              </blockquote>
            ))}
          </article>
          <article className="card" data-reveal>
            <h2>Recruiter Snapshot</h2>
            <p className="list-title">Education</p>
            <ul>
              {liveData.profile.experience.map((item) => (
                <li key={`${item.role}-${item.period}`}>
                  {item.role} ({item.period})
                </li>
              ))}
            </ul>
            <Link className="inline-link" href="/recruiters">
              Open recruiter page
            </Link>
          </article>
        </div>
      </section>

      <section className="section" data-reveal>
        <div className="container">
          <div className="section-head">
            <p className="eyebrow">Delivery Framework</p>
            <h2>How Enterprise Projects Are Executed</h2>
          </div>
          <div className="process-grid">
            <article className="card process-card" data-reveal>
              <LuxIcon name="discovery" className="lux-icon" />
              <p className="list-title">Discovery and Scope</p>
              <p>Clarify business goals, audience, KPIs, risk zones, and delivery constraints.</p>
            </article>
            <article className="card process-card" data-reveal>
              <LuxIcon name="build" className="lux-icon" />
              <p className="list-title">Architecture and Build</p>
              <p>Ship modular foundations, secure APIs, and premium interface systems.</p>
            </article>
            <article className="card process-card" data-reveal>
              <LuxIcon name="launch" className="lux-icon" />
              <p className="list-title">Launch and Optimization</p>
              <p>Measure conversion behavior, improve performance, and iterate based on real data.</p>
            </article>
          </div>
        </div>
      </section>

      <section className="section" data-reveal>
        <div className="container two-col">
          <article className="card" data-reveal>
            <h2>{audienceConfig[audience].cta}</h2>
            <p className="repo-meta">Step {leadStep} of 3</p>
            <form className="lead-form" onSubmit={submitLeadWithError}>
              <div className="step-pills">
                {[1, 2, 3].map((step) => (
                  <span key={step} className={`step-pill ${leadStep >= step ? "step-pill-active" : ""}`}>
                    {step}
                  </span>
                ))}
              </div>

              {leadStep === 1 && (
                <div className="audience-grid">
                  {(Object.keys(audienceConfig) as Audience[]).map((key) => (
                    <button
                      key={key}
                      type="button"
                      data-magnetic
                      className={`audience-card ${audience === key ? "audience-card-active" : ""}`}
                      onClick={() => setAudience(key)}
                    >
                      <p className="list-title">{audienceConfig[key].label}</p>
                      <p>{audienceConfig[key].subtitle}</p>
                    </button>
                  ))}
                </div>
              )}

              {leadStep === 2 && (
                <>
                  <input
                    required
                    placeholder="Your Name"
                    value={lead.name}
                    onChange={(event) => setLead({ ...lead, name: event.target.value })}
                  />
                  <input
                    required
                    type="email"
                    placeholder="Your Email"
                    value={lead.email}
                    onChange={(event) => setLead({ ...lead, email: event.target.value })}
                  />
                  <input
                    placeholder="Company"
                    value={lead.company}
                    onChange={(event) => setLead({ ...lead, company: event.target.value })}
                  />
                </>
              )}

              {leadStep === 3 && (
                <>
                  <p className="repo-meta">Interest: {lead.interest}</p>
                  <textarea
                    required
                    placeholder="Project goals, timeline, or hiring context"
                    value={lead.message}
                    onChange={(event) => setLead({ ...lead, message: event.target.value })}
                  />
                </>
              )}

              <div className="cta-row compact">
                {leadStep > 1 && (
                  <button className="btn btn-outline" data-magnetic type="button" onClick={() => setLeadStep((previous) => (previous - 1) as 1 | 2 | 3)}>
                    Back
                  </button>
                )}
                {leadStep < 3 && (
                  <button
                    className="btn btn-gold"
                    data-magnetic
                    type="button"
                    onClick={() => setLeadStep((previous) => (previous + 1) as 1 | 2 | 3)}
                    disabled={leadStep === 2 && !canProceedStepTwo}
                  >
                    Continue
                  </button>
                )}
                {leadStep === 3 && (
                  <button className="btn btn-gold" data-magnetic type="submit" disabled={leadState === "saving" || !canSubmit}>
                    {leadState === "saving" ? "Sending..." : "Submit Inquiry"}
                  </button>
                )}
              </div>

              {leadState === "done" && <p className="success">Inquiry sent. I will respond soon.</p>}
              {leadState === "error" && <p className="error">{leadError || "Could not send inquiry. Please try again."}</p>}
            </form>
          </article>

          <article className="card" data-reveal>
            <h2>Book a Discovery Call</h2>
            <p>
              Scheduling link:{" "}
              <a href="https://calendly.com" target="_blank" rel="noreferrer">
                Calendly
              </a>
            </p>
            <div className="calendly-placeholder">Embed your Calendly link here for real-time booking.</div>
            <h2>Policy and Trust</h2>
            <p>
              <Link href="/privacy-policy">Privacy Policy</Link> | <Link href="/terms">Terms</Link>
            </p>
          </article>
        </div>
      </section>
    </main>
  );
}
