export type Project = {
  title: string;
  slug: string;
  stack: string;
  summary: string[];
  outcomes: string[];
  github?: string;
  live?: string;
  tags: string[];
  featured?: boolean;
};

export type EducationItem = {
  role: string;
  org: string;
  period: string;
};

export type Testimonial = {
  name: string;
  role: string;
  quote: string;
};

export type Service = {
  slug: string;
  title: string;
  description: string;
  bullets: string[];
};

export type CaseStudy = {
  slug: string;
  title: string;
  challenge: string;
  approach: string[];
  outcome: string[];
  tech: string[];
};

export type BlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  date: string;
  readMinutes: number;
  content: string[];
  tags: string[];
};

export type SiteContent = {
  profile: {
    name: string;
    city: string;
    email: string;
    phone: string;
    github: string;
    linkedin: string;
    cvPath: string;
    tagline: string;
    about: string;
    highlights: string[];
    skills: {
      technologies: string[];
      dashboards: string[];
      databases: string[];
      additional: string[];
    };
    softSkills: string[];
    languages: string[];
    achievements: string[];
    experience: EducationItem[];
  };
  projects: Project[];
  services: Service[];
  caseStudies: CaseStudy[];
  testimonials: Testimonial[];
  clientLogos: string[];
  blogPosts: BlogPost[];
};

export type RuntimeProject = Project & {
  stars?: number;
  forks?: number;
  updatedAt?: string;
  autogenerated?: boolean;
};

export type RuntimeContent = Omit<SiteContent, "projects"> & {
  projects: RuntimeProject[];
  runtime: {
    githubFollowers: number | null;
    githubRepos: number | null;
    totalStars: number | null;
    syncedRepos: number;
    generatedAt: string;
    timezone: string;
  };
};

export type LeadRecord = {
  id: string;
  name: string;
  email: string;
  company: string;
  interest: string;
  message: string;
  createdAt: string;
};
